# config.toml

# To use ExportifyX you need to provide your Spotify API credentials, the following instructions will walk you through the setup.

# === User Setup Instructions ===
# 1. Go to "https://developer.spotify.com/dashboard/applications".
# 2. Login with your spotify account.
# 3. Click 'Create An App' and fill in the required details.
# 4. After creating the app you will be given a "CLIENT ID" and "CLIENT SECRET".
# 5. Paste your "CLIENT ID" and "CLIENT SECRET" into the fields below.
# 6. Save the file and start using ExportifyX!

[spotify]
client_id = "your_client_id"
client_secret = "your_client_secret"

[output]
output_dir = "playlists"
create_folder = true

[webgui]
port = 5050
